import { ArrowUpRight } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { DocSection, DocsLayout, Status } from "@/components/docs-layout";
import { LINKS, MODULES } from "@/lib/synra";

const moduleCopy:Record<string,{title:string;focus:string[]}>= {
 pay:{title:"SYNRA PAY",focus:["Payments","Digital value","Stablecoin infrastructure","Global connectivity"]},
 flow:{title:"SYNRA FLOW",focus:["Liquidity movement","Routing","Capital flow","Connected financial infrastructure"]},
 market:{title:"SYNRA MARKET",focus:["Onchain markets","Digital assets","Market connectivity","Financial opportunities"]},
 vault:{title:"SYNRA VAULT",focus:["Capital management","Digital assets","Future financial strategies"]},
};
export function OverviewDoc(){return <DocsLayout title="SYNRA DOCUMENTATION" eyebrow="THE FINANCIAL GRID FOR A MORE OPEN ECONOMY" toc={["What is SYNRA","Synchronized Value Rails","The Ecosystem","Why Arc"]}><p className="doc-lead">SYNRA is a programmable financial network concept built for the next generation of digital value.</p><DocSection title="What is SYNRA"><p>The Financial Grid exists to explore an internet-native environment where people, capital, payments, liquidity, markets, applications and opportunities interact through programmable rails.</p></DocSection><DocSection title="Synchronized Value Rails"><p><strong>SYN</strong> represents synchronized. <strong>RA</strong> reflects rails and architecture. Together, “Synchronized Value Rails” expresses the project’s brand philosophy, not an official legal acronym.</p></DocSection><DocSection title="The Ecosystem"><div className="architecture-stack">{MODULES.map((m,i)=><div key={m.key}><span>0{i+1}</span><strong>{m.title} · {m.status}</strong></div>)}</div></DocSection><DocSection title="Why Arc"><p>Arc’s focus on stablecoin-native finance, payments and settlement makes it a relevant foundation for SYNRA’s exploration of programmable financial infrastructure.</p></DocSection></DocsLayout>}
export function LoreDoc(){return <DocsLayout title="THE SYNRA LORE" toc={["Fragmented Value","The Question","The Financial Grid"]}><DocSection title="Fragmented Value"><p>For decades, money moved through institutions, banks and fragmented payment networks. The internet changed how information moves. But value remained constrained by legacy infrastructure.</p><p>Then stablecoins introduced programmable digital money.</p></DocSection><DocSection title="The Question"><p className="doc-lead">What happens when financial infrastructure is designed for the internet from the beginning?</p><p>SYNRA emerged from this question: a network built around connected financial rails.</p></DocSection><DocSection title="The Financial Grid"><p>Payments. Liquidity. Markets. Capital. Digital assets. Applications. All connected through one idea: <strong>THE FINANCIAL GRID.</strong></p><div className="doc-callout">THE INTERNET CONNECTED PEOPLE.<br/>STABLECOINS CONNECTED MONEY.<br/><strong>SYNRA CONNECTS THE ECONOMY.</strong></div></DocSection></DocsLayout>}
export function VisionDoc(){return <DocsLayout title="A MORE OPEN ECONOMY" toc={["The Vision","Open Infrastructure","Opportunity"]}><p className="doc-lead">A financial environment where global value can move, settle and interact through programmable infrastructure.</p><DocSection title="The Vision"><p>SYNRA’s vision connects programmable finance, markets, liquidity, capital, digital assets and settlement through a shared architecture.</p></DocSection><DocSection title="Open Infrastructure"><p>Composability allows financial components and applications to build upon one another. Transparent onchain infrastructure can make activity verifiable while keeping connectivity global.</p></DocSection><DocSection title="Opportunity"><p>A more open economy expands the ways people and applications can participate in digital value. This is a vision under development, not a claim of currently live products.</p></DocSection></DocsLayout>}
export function FinancialGridDoc(){return <DocsLayout title="THE FINANCIAL GRID" toc={["Architecture","Layers","Value Flow"]}><p className="doc-lead">A connected architecture for value, payments, settlement, liquidity, markets, capital and applications.</p><DocSection title="Architecture"><p>The Financial Grid is SYNRA’s core conceptual model. Each layer has a distinct role while remaining connected through programmable financial rails.</p></DocSection><DocSection title="Layers"><div className="architecture-stack">{['VALUE','PAYMENTS','SETTLEMENT','LIQUIDITY','MARKETS','CAPITAL','APPLICATIONS'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></DocSection><DocSection title="Value Flow"><p>Connections between the layers represent purpose-driven value movement—not decorative data. The architecture is a conceptual framework currently in development.</p></DocSection></DocsLayout>}
export function ModuleDoc({kind}:{kind:string}){const d=moduleCopy[kind];const m=MODULES.find(x=>x.key===kind.toUpperCase());if(!d||!m)return null;return <DocsLayout title={d.title} toc={["Conceptual Role","Focus","Status"]}><p className="doc-lead">{m.description}</p><DocSection title="Conceptual Role"><p>{kind==='pay'?'SYNRA PAY explores payment infrastructure for moving digital value through stablecoin-native rails.':kind==='flow'?'SYNRA FLOW explores how liquidity and capital could move and route across connected financial infrastructure.':kind==='market'?'SYNRA MARKET explores an onchain market layer connecting participants, digital assets and financial opportunities.':'SYNRA VAULT explores a future capital layer for digital asset management and financial strategies.'}</p></DocSection><DocSection title="Focus"><ul>{d.focus.map(x=><li key={x}>{x}</li>)}</ul></DocSection><DocSection title="Status"><Status>PLANNED</Status><p>This module is conceptual and is not presented as a live product.</p></DocSection></DocsLayout>}
export function ArcDoc(){return <DocsLayout title="SYNRA × ARC" toc={["Relationship","Why Arc","Independence"]}><p className="doc-lead">SYNRA is an independent project built within the Arc ecosystem.</p><DocSection title="Relationship"><p>Arc is developed by Circle and is positioned as a blockchain designed specifically for stablecoin finance.</p></DocSection><DocSection title="Why Arc"><p>Relevant capabilities include USDC-native gas, stablecoin-native infrastructure, fast deterministic finality, EVM compatibility, payments, settlement, capital markets, FX and tokenization.</p><Button asChild variant="outline"><a href={LINKS.ARC_URL} target="_blank" rel="noreferrer">EXPLORE ARC <ArrowUpRight/></a></Button></DocSection><DocSection title="Independence"><div className="doc-callout"><strong>SYNRA is an independent project and is not an official Circle or Arc product.</strong></div></DocSection></DocsLayout>}
export function TokenDoc(){return <DocsLayout title="$SYNRA" toc={["Token Information","Availability"]}><p className="doc-lead">The native asset of the SYNRA ecosystem.</p><DocSection title="Token Information"><div className="doc-data">{[['TOKEN','$SYNRA'],['NETWORK','ARC'],['CONTRACT','COMING SOON'],['TOKENOMICS','COMING SOON'],['UTILITY','COMING SOON']].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></DocSection><DocSection title="Availability"><p>Contract and token details will be announced through official SYNRA channels. Never trust an unverified contract address.</p><div className="cta-row"><Button asChild><a href={LINKS.ARGUSPAD_URL} target="_blank" rel="noreferrer">BUY $SYNRA</a></Button><Button asChild variant="outline"><a href={LINKS.ARGUSPAD_URL} target="_blank" rel="noreferrer">CHART</a></Button></div></DocSection></DocsLayout>}
export function RoadmapDoc(){const phases=[['01','FOUNDATION','Website, brand, documentation and community.','IN DEVELOPMENT'],['02','GRID','Architecture, core ecosystem development and the Financial Grid.','IN DEVELOPMENT'],['03','PRODUCT','PAY, FLOW, MARKET and VAULT.','PLANNED'],['04','ECOSYSTEM','Applications, liquidity, markets and integrations.','PLANNED'],['05','EXPANSION','New financial primitives, global ecosystem and future integrations.','VISION']];return <DocsLayout title="THE ROAD AHEAD" toc={["Roadmap","Status Definitions"]}><DocSection title="Roadmap"><div className="architecture-stack">{phases.map(([n,t,c,s])=><div key={n}><span>{n}</span><p><strong>{t}</strong><br/>{c}<br/><Status>{s}</Status></p></div>)}</div></DocSection><DocSection title="Status Definitions"><p><strong>IN DEVELOPMENT</strong> denotes active foundational work. <strong>PLANNED</strong> marks intended future modules. <strong>VISION</strong> describes a long-term direction. No future feature is represented as live.</p></DocSection></DocsLayout>}
const faqs=[['What is SYNRA?','A programmable financial network concept built for the next generation of digital value.'],['What is the Financial Grid?','A connected financial architecture for payments, liquidity, markets, capital and applications.'],['What does SYNRA mean?','Synchronized Value Rails is the project’s preferred brand philosophy, not an official legal acronym.'],['What are Synchronized Value Rails?','Programmable infrastructure designed to connect and coordinate the movement of digital value.'],['Why is SYNRA built on Arc?','Arc is designed around stablecoin finance, payments and settlement.'],['What is SYNRA PAY?','A planned conceptual payment layer.'],['What is SYNRA FLOW?','A planned conceptual liquidity movement and routing layer.'],['What is SYNRA MARKET?','A planned conceptual onchain market layer.'],['What is SYNRA VAULT?','A planned conceptual capital management layer.'],['What is the SYNRA Grid?','The core conceptual architecture connecting the ecosystem.'],['What is $SYNRA?','The planned native asset of the SYNRA ecosystem.'],['What is the contract address?','COMING SOON'],['When will the contract be announced?','COMING SOON. Follow the official SYNRA X account for updates.'],['Where can I buy $SYNRA?','Official access is linked through ArgusPad. Verify all information through official SYNRA channels.'],['Where can I view the chart?','The official chart link points to ArgusPad.'],['Is SYNRA an official Circle project?','No. SYNRA is an independent project and is not an official Circle or Arc product.'],['How can I follow SYNRA?','Follow @SYNRAonChain on X.']];
export function FaqDoc(){return <DocsLayout title="FREQUENTLY ASKED QUESTIONS" toc={["General Questions"]}><DocSection title="General Questions"><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem value={`q${i}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></DocSection></DocsLayout>}
export function DisclaimerDoc(){return <DocsLayout title="DISCLAIMER" toc={["Independent Project","Information","Responsibility"]}><DocSection title="Independent Project"><p>SYNRA is an independent project. SYNRA is not Circle and is not Arc. References to Arc describe the underlying ecosystem and infrastructure.</p></DocSection><DocSection title="Information"><p>Nothing on this website constitutes financial, legal or investment advice. Token information can change. Contract information should only be trusted when published through official SYNRA channels.</p></DocSection><DocSection title="Responsibility"><p>Digital assets involve risk. Users should conduct their own research and independently verify all information before taking action.</p></DocSection></DocsLayout>}
export function ChangelogDoc(){return <DocsLayout title="CHANGELOG" toc={["2026"]}><DocSection title="2026"><h3>FOUNDATION</h3><p>SYNRA website and documentation foundation.</p></DocSection></DocsLayout>}